config/routes.rb
Rails.application.routes.draw do

  get 'chats/show'
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :searches, only: [:index]
  # post 'conversations/create' => 'conversations#create'

  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :users,only: [:show,:index,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end

end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

  has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user


	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  is_impressionable counter_cache: true

  # def Book.last_week # メソッド名は何でも良いです
    # Book.joins(:favorites).where(favorites: { created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(*) desc")
  # end

  def Book.search(search, model, how)
    if how == "partical"
  	  Book.where("title LIKE ?", "%#{search}%")
    elsif how == "forward"
  	  Book.where("title LIKE ?", "#{search}%")
    elsif how == "backward"
  	  Book.where("title LIKE ?", "%#{search}")
    elsif how == "match"
  	  Book.where("title LIKE ?", "#{search}")
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @booknew = Book.new
    @post_comment = PostComment.new
    impressionist(@book, nil, unique: [:ip_address])
  end

  def index
    @book = Book.new
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.includes(:favorites).where(created_at: Time.current.all_week).size <=> a.favorited_users.includes(:favorites).where(created_at: Time.current.all_week).size}

    # Book.includes(:favorited_users).where(created_at: Time.current.all_week).group(:id).order("count(*) desc")
    # Book.joins(:favorites).where(favorites: { created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(*) desc")
    # Book.joins(:favorites).where(favorites: { created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(*) desc")
    # Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    # @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(10),pluck(:book_id))
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">

        <%= render "favorites/favorites", book: book %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

       <% if @book.errors.any? %>
        <%= @book.errors.count %> error prohibited this obj from being saved:
        <br><% @book.errors.full_messages.each do |message| %>
          ・<%= message %>
        <% end %>
      <% end %>

      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books, book: @book %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book, book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.user) %></td>
          <td><%= @book.body %></td>



           <% if @book.user.id == current_user.id %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% else %>
              <td><% if @book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(@book), method: :delete do %>
                        ♥<%= @book.favorites.count %>
                      <% end %>
                    </p>
                  <% else %>
                    <p>
                      <%= link_to book_favorites_path(@book), method: :post do %>
                        ♡<%= @book.favorites.count %>
                      <% end %>
                    </p>
                  <% end %>
              </td>
              <td><p>コメント件数：<%= @book.post_comments.count %></p></td>
            <% end %>
        </tr>
      </table>

        <table>
          <%= render 'post_comments/index', book: @book %>
        </table>

      <div>
        <%= form_with model:[@book, @post_comment] do |f| %>
        <%= f.text_area :comment, rows:'5' %>
        <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>